plugins {
    id 'com.android.application'
}

android {
    namespace 'com.orbita.aurora'
    compileSdk 37

    defaultConfig {
        applicationId 'com.orbita.aurora'
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }

        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles(
                getDefaultProguardFile('proguard-android-optimize.txt'),
                'proguard-rules.pro'
            )
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += [
                '/META-INF/{AL2.0,LGPL2.1}',
                '/META-INF/DEPENDENCIES'
            ]
        }
    }
}

dependencies {
    implementation 'org.mozilla.geckoview:geckoview-stable:157.0.20260909211052'
}
